fix: Increase strategies limit
snapshot-labs/score-api pull request #998
Opened 2023-12-23 19:25 UTC by ChaituVR

This will increase strategies limit from `8` to `10`

Refer https://discord.com/channels/955773041898573854/1187284357799481484/1188191395261972640

2023-12-24 05:35 UTC, wa0x6e commented on src/rpc.ts
> +      params.strategies.length > 10
We could extract `10` to a constant, and avoid having to edit test files in case of update

2023-12-27 08:01 UTC, wa0x6e requested changes

2023-12-27 08:01 UTC, wa0x6e commented on src/utils.test.ts
> +    const strategies = new Array(12).fill({ name: 'strategy', param: 'a' });
Could use something like `MAX_STRATEGIES + 1`

2023-12-27 09:06 UTC, wa0x6e approved these changes
utAck

2023-12-27 09:08 UTC, ChaituVR commented on src/utils.test.ts
> +    const strategies = new Array(12).fill({ name: 'strategy', param: 'a' });
Nice catch 👍

2023-12-27 09:10 UTC, merged